import { useLocalStorage } from './useLocalStorage';

// Real translations for navigation/button labels in major languages.
// Languages not listed here fall back to English. For AI responses,
// the language preference is sent to the model which responds in that language.

type Dict = Record<string, string>;

const translations: Record<string, Dict> = {
  English: {},
  Hindi: { home: 'होम', dashboard: 'डैशबोर्ड', symptoms: 'लक्षण', skinInjury: 'त्वचा और चोट', chat: 'चैट', fitness: 'फिटनेस', medicine: 'दवा', vitals: 'जीवन संकेत', reportAnalysis: 'रिपोर्ट विश्लेषण', healthCalculator: 'स्वास्थ्य कैलकुलेटर', medReminders: 'दवा अनुस्मारक', reportsHub: 'रिपोर्ट हब', posture: 'मुद्रा', firstAid: 'प्राथमिक चिकित्सा', healthTips: 'स्वास्थ्य सुझाव', emergency: 'आपातकाल', howToUse: 'कैसे उपयोग करें', settings: 'सेटिंग्स', about: 'हमारे बारे में', more: 'और', login: 'लॉगिन', signOut: 'साइन आउट', chatWithAI: 'AI से चैट', language: 'भाषा', analyze: 'विश्लेषण करें', upload: 'अपलोड', camera: 'कैमरा', capture: 'कैप्चर', cancel: 'रद्द करें', search: 'खोजें', allHealthTools: 'सभी स्वास्थ्य उपकरण', tagline: 'अपने जीवन को स्वस्थ बनाएं!' },
  Spanish: { home: 'Inicio', dashboard: 'Panel', symptoms: 'Síntomas', skinInjury: 'Piel y lesiones', chat: 'Chat', fitness: 'Fitness', medicine: 'Medicina', vitals: 'Signos vitales', reportAnalysis: 'Análisis de informe', healthCalculator: 'Calculadora', medReminders: 'Recordatorios', reportsHub: 'Informes', posture: 'Postura', firstAid: 'Primeros auxilios', healthTips: 'Consejos', emergency: 'Emergencia', howToUse: 'Cómo usar', settings: 'Ajustes', about: 'Acerca de', more: 'Más', login: 'Iniciar sesión', signOut: 'Cerrar sesión', chatWithAI: 'Chat con IA', language: 'Idioma', analyze: 'Analizar', upload: 'Subir', camera: 'Cámara', capture: 'Capturar', cancel: 'Cancelar', search: 'Buscar', allHealthTools: 'Todas las herramientas', tagline: '¡Haz tu vida más saludable!' },
  French: { home: 'Accueil', dashboard: 'Tableau de bord', symptoms: 'Symptômes', skinInjury: 'Peau et blessures', chat: 'Chat', fitness: 'Fitness', medicine: 'Médecine', vitals: 'Signes vitaux', reportAnalysis: 'Analyse de rapport', healthCalculator: 'Calculatrice', medReminders: 'Rappels', reportsHub: 'Rapports', posture: 'Posture', firstAid: 'Premiers secours', healthTips: 'Conseils santé', emergency: 'Urgence', howToUse: 'Comment utiliser', settings: 'Paramètres', about: 'À propos', more: 'Plus', login: 'Connexion', signOut: 'Déconnexion', chatWithAI: 'Chat IA', language: 'Langue', analyze: 'Analyser', upload: 'Téléverser', camera: 'Caméra', capture: 'Capturer', cancel: 'Annuler', search: 'Rechercher', allHealthTools: 'Tous les outils', tagline: 'Rendez votre vie plus saine!' },
  German: { home: 'Startseite', dashboard: 'Dashboard', symptoms: 'Symptome', skinInjury: 'Haut & Verletzung', chat: 'Chat', fitness: 'Fitness', medicine: 'Medizin', vitals: 'Vitalwerte', reportAnalysis: 'Berichtsanalyse', healthCalculator: 'Rechner', medReminders: 'Erinnerungen', reportsHub: 'Berichte', posture: 'Haltung', firstAid: 'Erste Hilfe', healthTips: 'Gesundheitstipps', emergency: 'Notfall', howToUse: 'Anleitung', settings: 'Einstellungen', about: 'Über', more: 'Mehr', login: 'Anmelden', signOut: 'Abmelden', chatWithAI: 'KI-Chat', language: 'Sprache', analyze: 'Analysieren', upload: 'Hochladen', camera: 'Kamera', capture: 'Aufnehmen', cancel: 'Abbrechen', search: 'Suchen', allHealthTools: 'Alle Tools', tagline: 'Mache dein Leben gesünder!' },
  Italian: { home: 'Home', dashboard: 'Dashboard', symptoms: 'Sintomi', skinInjury: 'Pelle e lesioni', chat: 'Chat', fitness: 'Fitness', medicine: 'Medicina', vitals: 'Parametri vitali', reportAnalysis: 'Analisi referto', healthCalculator: 'Calcolatore', medReminders: 'Promemoria', reportsHub: 'Referti', posture: 'Postura', firstAid: 'Primo soccorso', healthTips: 'Consigli', emergency: 'Emergenza', howToUse: 'Come usare', settings: 'Impostazioni', about: 'Informazioni', more: 'Altro', login: 'Accedi', signOut: 'Esci', chatWithAI: 'Chat con IA', language: 'Lingua', analyze: 'Analizza', upload: 'Carica', camera: 'Fotocamera', capture: 'Cattura', cancel: 'Annulla', search: 'Cerca', allHealthTools: 'Tutti gli strumenti', tagline: 'Rendi la tua vita più sana!' },
  Portuguese: { home: 'Início', dashboard: 'Painel', symptoms: 'Sintomas', skinInjury: 'Pele e lesão', chat: 'Chat', fitness: 'Fitness', medicine: 'Medicina', vitals: 'Sinais vitais', reportAnalysis: 'Análise de relatório', healthCalculator: 'Calculadora', medReminders: 'Lembretes', reportsHub: 'Relatórios', posture: 'Postura', firstAid: 'Primeiros socorros', healthTips: 'Dicas', emergency: 'Emergência', howToUse: 'Como usar', settings: 'Configurações', about: 'Sobre', more: 'Mais', login: 'Entrar', signOut: 'Sair', chatWithAI: 'Chat com IA', language: 'Idioma', analyze: 'Analisar', upload: 'Enviar', camera: 'Câmera', capture: 'Capturar', cancel: 'Cancelar', search: 'Buscar', allHealthTools: 'Todas as ferramentas', tagline: 'Torne sua vida mais saudável!' },
  Russian: { home: 'Главная', dashboard: 'Панель', symptoms: 'Симптомы', skinInjury: 'Кожа и травмы', chat: 'Чат', fitness: 'Фитнес', medicine: 'Медицина', vitals: 'Жизненные показатели', reportAnalysis: 'Анализ отчёта', healthCalculator: 'Калькулятор', medReminders: 'Напоминания', reportsHub: 'Отчёты', posture: 'Осанка', firstAid: 'Первая помощь', healthTips: 'Советы', emergency: 'Экстренная помощь', howToUse: 'Как использовать', settings: 'Настройки', about: 'О нас', more: 'Ещё', login: 'Войти', signOut: 'Выйти', chatWithAI: 'Чат с ИИ', language: 'Язык', analyze: 'Анализ', upload: 'Загрузить', camera: 'Камера', capture: 'Снимок', cancel: 'Отмена', search: 'Поиск', allHealthTools: 'Все инструменты', tagline: 'Сделайте свою жизнь здоровее!' },
  Japanese: { home: 'ホーム', dashboard: 'ダッシュボード', symptoms: '症状', skinInjury: '肌と怪我', chat: 'チャット', fitness: 'フィットネス', medicine: '薬', vitals: 'バイタル', reportAnalysis: 'レポート分析', healthCalculator: '計算機', medReminders: 'リマインダー', reportsHub: 'レポート', posture: '姿勢', firstAid: '応急処置', healthTips: '健康のヒント', emergency: '緊急', howToUse: '使い方', settings: '設定', about: '概要', more: 'もっと', login: 'ログイン', signOut: 'ログアウト', chatWithAI: 'AIチャット', language: '言語', analyze: '分析', upload: 'アップロード', camera: 'カメラ', capture: '撮影', cancel: 'キャンセル', search: '検索', allHealthTools: 'すべてのツール', tagline: 'あなたの人生をより健康に!' },
  Korean: { home: '홈', dashboard: '대시보드', symptoms: '증상', skinInjury: '피부 및 부상', chat: '채팅', fitness: '피트니스', medicine: '약', vitals: '활력 징후', reportAnalysis: '보고서 분석', healthCalculator: '계산기', medReminders: '알림', reportsHub: '보고서', posture: '자세', firstAid: '응급 처치', healthTips: '건강 팁', emergency: '응급', howToUse: '사용 방법', settings: '설정', about: '정보', more: '더보기', login: '로그인', signOut: '로그아웃', chatWithAI: 'AI 채팅', language: '언어', analyze: '분석', upload: '업로드', camera: '카메라', capture: '캡처', cancel: '취소', search: '검색', allHealthTools: '모든 도구', tagline: '당신의 삶을 더 건강하게!' },
  'Chinese (Simplified)': { home: '首页', dashboard: '仪表板', symptoms: '症状', skinInjury: '皮肤与伤害', chat: '聊天', fitness: '健身', medicine: '药物', vitals: '生命体征', reportAnalysis: '报告分析', healthCalculator: '计算器', medReminders: '提醒', reportsHub: '报告中心', posture: '姿势', firstAid: '急救', healthTips: '健康贴士', emergency: '紧急', howToUse: '使用方法', settings: '设置', about: '关于', more: '更多', login: '登录', signOut: '退出', chatWithAI: 'AI聊天', language: '语言', analyze: '分析', upload: '上传', camera: '相机', capture: '拍摄', cancel: '取消', search: '搜索', allHealthTools: '所有工具', tagline: '让您的生活更健康！' },
  'Chinese (Traditional)': { home: '首頁', dashboard: '儀表板', symptoms: '症狀', skinInjury: '皮膚與傷害', chat: '聊天', fitness: '健身', medicine: '藥物', vitals: '生命徵象', reportAnalysis: '報告分析', healthCalculator: '計算器', medReminders: '提醒', reportsHub: '報告中心', posture: '姿勢', firstAid: '急救', healthTips: '健康貼士', emergency: '緊急', howToUse: '使用方法', settings: '設定', about: '關於', more: '更多', login: '登入', signOut: '登出', chatWithAI: 'AI聊天', language: '語言', analyze: '分析', upload: '上傳', camera: '相機', capture: '拍攝', cancel: '取消', search: '搜尋', allHealthTools: '所有工具', tagline: '讓您的生活更健康！' },
  Arabic: { home: 'الرئيسية', dashboard: 'لوحة التحكم', symptoms: 'الأعراض', skinInjury: 'الجلد والإصابة', chat: 'دردشة', fitness: 'لياقة', medicine: 'دواء', vitals: 'العلامات الحيوية', reportAnalysis: 'تحليل التقرير', healthCalculator: 'حاسبة', medReminders: 'تذكير', reportsHub: 'التقارير', posture: 'وضعية', firstAid: 'إسعافات أولية', healthTips: 'نصائح صحية', emergency: 'طوارئ', howToUse: 'طريقة الاستخدام', settings: 'الإعدادات', about: 'حول', more: 'المزيد', login: 'تسجيل الدخول', signOut: 'تسجيل الخروج', chatWithAI: 'دردشة AI', language: 'اللغة', analyze: 'تحليل', upload: 'رفع', camera: 'كاميرا', capture: 'التقاط', cancel: 'إلغاء', search: 'بحث', allHealthTools: 'جميع الأدوات', tagline: 'اجعل حياتك أكثر صحة!' },
  Bengali: { home: 'হোম', dashboard: 'ড্যাশবোর্ড', symptoms: 'লক্ষণ', skinInjury: 'ত্বক ও আঘাত', chat: 'চ্যাট', fitness: 'ফিটনেস', medicine: 'ওষুধ', vitals: 'গুরুত্বপূর্ণ লক্ষণ', reportAnalysis: 'রিপোর্ট বিশ্লেষণ', healthCalculator: 'ক্যালকুলেটর', medReminders: 'রিমাইন্ডার', reportsHub: 'রিপোর্ট হাব', posture: 'ভঙ্গি', firstAid: 'প্রাথমিক চিকিৎসা', healthTips: 'স্বাস্থ্য টিপস', emergency: 'জরুরি', howToUse: 'ব্যবহারবিধি', settings: 'সেটিংস', about: 'সম্পর্কে', more: 'আরও', login: 'লগইন', signOut: 'লগআউট', chatWithAI: 'AI চ্যাট', language: 'ভাষা', analyze: 'বিশ্লেষণ', upload: 'আপলোড', camera: 'ক্যামেরা', capture: 'ক্যাপচার', cancel: 'বাতিল', search: 'অনুসন্ধান', allHealthTools: 'সব সরঞ্জাম', tagline: 'আপনার জীবন স্বাস্থ্যকর করুন!' },
  Turkish: { home: 'Ana Sayfa', dashboard: 'Panel', symptoms: 'Belirtiler', skinInjury: 'Cilt ve Yaralanma', chat: 'Sohbet', fitness: 'Fitness', medicine: 'İlaç', vitals: 'Yaşam Belirtileri', reportAnalysis: 'Rapor Analizi', healthCalculator: 'Hesaplayıcı', medReminders: 'Hatırlatıcılar', reportsHub: 'Raporlar', posture: 'Duruş', firstAid: 'İlk Yardım', healthTips: 'Sağlık İpuçları', emergency: 'Acil', howToUse: 'Nasıl Kullanılır', settings: 'Ayarlar', about: 'Hakkında', more: 'Daha', login: 'Giriş', signOut: 'Çıkış', chatWithAI: 'AI ile Sohbet', language: 'Dil', analyze: 'Analiz', upload: 'Yükle', camera: 'Kamera', capture: 'Yakala', cancel: 'İptal', search: 'Ara', allHealthTools: 'Tüm Araçlar', tagline: 'Hayatınızı daha sağlıklı yapın!' },
  Dutch: { home: 'Home', dashboard: 'Dashboard', symptoms: 'Symptomen', skinInjury: 'Huid & Letsel', chat: 'Chat', fitness: 'Fitness', medicine: 'Medicijn', vitals: 'Vitale waarden', reportAnalysis: 'Rapportanalyse', healthCalculator: 'Calculator', medReminders: 'Herinneringen', reportsHub: 'Rapporten', posture: 'Houding', firstAid: 'EHBO', healthTips: 'Gezondheidstips', emergency: 'Noodgeval', howToUse: 'Gebruik', settings: 'Instellingen', about: 'Over', more: 'Meer', login: 'Inloggen', signOut: 'Uitloggen', chatWithAI: 'AI Chat', language: 'Taal', analyze: 'Analyseren', upload: 'Uploaden', camera: 'Camera', capture: 'Vastleggen', cancel: 'Annuleren', search: 'Zoeken', allHealthTools: 'Alle tools', tagline: 'Maak je leven gezonder!' },
  Polish: { home: 'Start', dashboard: 'Panel', symptoms: 'Objawy', skinInjury: 'Skóra i urazy', chat: 'Czat', fitness: 'Fitness', medicine: 'Leki', vitals: 'Parametry życiowe', reportAnalysis: 'Analiza raportu', healthCalculator: 'Kalkulator', medReminders: 'Przypomnienia', reportsHub: 'Raporty', posture: 'Postawa', firstAid: 'Pierwsza pomoc', healthTips: 'Porady zdrowotne', emergency: 'Nagły wypadek', howToUse: 'Jak używać', settings: 'Ustawienia', about: 'O nas', more: 'Więcej', login: 'Zaloguj', signOut: 'Wyloguj', chatWithAI: 'Czat AI', language: 'Język', analyze: 'Analizuj', upload: 'Prześlij', camera: 'Kamera', capture: 'Zrób zdjęcie', cancel: 'Anuluj', search: 'Szukaj', allHealthTools: 'Wszystkie narzędzia', tagline: 'Zrób swoje życie zdrowszym!' },
  Indonesian: { home: 'Beranda', dashboard: 'Dasbor', symptoms: 'Gejala', skinInjury: 'Kulit & Cedera', chat: 'Obrolan', fitness: 'Kebugaran', medicine: 'Obat', vitals: 'Tanda Vital', reportAnalysis: 'Analisis Laporan', healthCalculator: 'Kalkulator', medReminders: 'Pengingat', reportsHub: 'Laporan', posture: 'Postur', firstAid: 'P3K', healthTips: 'Tips Kesehatan', emergency: 'Darurat', howToUse: 'Cara Pakai', settings: 'Pengaturan', about: 'Tentang', more: 'Lainnya', login: 'Masuk', signOut: 'Keluar', chatWithAI: 'Chat AI', language: 'Bahasa', analyze: 'Analisis', upload: 'Unggah', camera: 'Kamera', capture: 'Ambil', cancel: 'Batal', search: 'Cari', allHealthTools: 'Semua alat', tagline: 'Buat hidupmu lebih sehat!' },
  Vietnamese: { home: 'Trang chủ', dashboard: 'Bảng điều khiển', symptoms: 'Triệu chứng', skinInjury: 'Da & Chấn thương', chat: 'Trò chuyện', fitness: 'Thể hình', medicine: 'Thuốc', vitals: 'Dấu hiệu sinh tồn', reportAnalysis: 'Phân tích báo cáo', healthCalculator: 'Máy tính', medReminders: 'Nhắc nhở', reportsHub: 'Báo cáo', posture: 'Tư thế', firstAid: 'Sơ cứu', healthTips: 'Mẹo sức khỏe', emergency: 'Khẩn cấp', howToUse: 'Cách dùng', settings: 'Cài đặt', about: 'Giới thiệu', more: 'Thêm', login: 'Đăng nhập', signOut: 'Đăng xuất', chatWithAI: 'Trò chuyện AI', language: 'Ngôn ngữ', analyze: 'Phân tích', upload: 'Tải lên', camera: 'Máy ảnh', capture: 'Chụp', cancel: 'Hủy', search: 'Tìm kiếm', allHealthTools: 'Tất cả công cụ', tagline: 'Làm cuộc sống của bạn khỏe mạnh hơn!' },
  Thai: { home: 'หน้าแรก', dashboard: 'แดชบอร์ด', symptoms: 'อาการ', skinInjury: 'ผิวและบาดเจ็บ', chat: 'แชท', fitness: 'ฟิตเนส', medicine: 'ยา', vitals: 'สัญญาณชีพ', reportAnalysis: 'วิเคราะห์รายงาน', healthCalculator: 'เครื่องคำนวณ', medReminders: 'เตือนความจำ', reportsHub: 'รายงาน', posture: 'ท่าทาง', firstAid: 'ปฐมพยาบาล', healthTips: 'เคล็ดลับสุขภาพ', emergency: 'ฉุกเฉิน', howToUse: 'วิธีใช้', settings: 'ตั้งค่า', about: 'เกี่ยวกับ', more: 'เพิ่มเติม', login: 'เข้าสู่ระบบ', signOut: 'ออกจากระบบ', chatWithAI: 'แชท AI', language: 'ภาษา', analyze: 'วิเคราะห์', upload: 'อัปโหลด', camera: 'กล้อง', capture: 'ถ่าย', cancel: 'ยกเลิก', search: 'ค้นหา', allHealthTools: 'เครื่องมือทั้งหมด', tagline: 'ทำให้ชีวิตของคุณมีสุขภาพดีขึ้น!' },
  Urdu: { home: 'ہوم', dashboard: 'ڈیش بورڈ', symptoms: 'علامات', skinInjury: 'جلد اور چوٹ', chat: 'چیٹ', fitness: 'فٹنس', medicine: 'دوا', vitals: 'حیاتی علامات', reportAnalysis: 'رپورٹ کا تجزیہ', healthCalculator: 'کیلکولیٹر', medReminders: 'یاد دہانی', reportsHub: 'رپورٹس', posture: 'اندازِ نشست', firstAid: 'ابتدائی طبی امداد', healthTips: 'صحت کی تجاویز', emergency: 'ہنگامی', howToUse: 'استعمال کا طریقہ', settings: 'ترتیبات', about: 'ہمارے بارے میں', more: 'مزید', login: 'لاگ ان', signOut: 'لاگ آؤٹ', chatWithAI: 'AI چیٹ', language: 'زبان', analyze: 'تجزیہ', upload: 'اپ لوڈ', camera: 'کیمرہ', capture: 'تصویر لیں', cancel: 'منسوخ', search: 'تلاش', allHealthTools: 'تمام ٹولز', tagline: 'اپنی زندگی کو صحت مند بنائیں!' },
  Tamil: { home: 'முகப்பு', dashboard: 'டாஷ்போர்டு', symptoms: 'அறிகுறிகள்', skinInjury: 'தோல் & காயம்', chat: 'அரட்டை', fitness: 'உடற்தகுதி', medicine: 'மருந்து', vitals: 'உயிர் அறிகுறிகள்', reportAnalysis: 'அறிக்கை பகுப்பாய்வு', healthCalculator: 'கால்குலேட்டர்', medReminders: 'நினைவூட்டல்', reportsHub: 'அறிக்கைகள்', posture: 'தோரணை', firstAid: 'முதலுதவி', healthTips: 'சுகாதார குறிப்புகள்', emergency: 'அவசரம்', howToUse: 'எப்படி பயன்படுத்துவது', settings: 'அமைப்புகள்', about: 'பற்றி', more: 'மேலும்', login: 'உள்நுழை', signOut: 'வெளியேறு', chatWithAI: 'AI அரட்டை', language: 'மொழி', analyze: 'பகுப்பாய்வு', upload: 'பதிவேற்று', camera: 'கேமரா', capture: 'எடு', cancel: 'ரத்து', search: 'தேடு', allHealthTools: 'அனைத்து கருவிகள்', tagline: 'உங்கள் வாழ்க்கையை ஆரோக்கியமாக்குங்கள்!' },
  Marathi: { home: 'मुख्यपृष्ठ', dashboard: 'डॅशबोर्ड', symptoms: 'लक्षणे', skinInjury: 'त्वचा व इजा', chat: 'चॅट', fitness: 'फिटनेस', medicine: 'औषध', vitals: 'जीवनलक्षणे', reportAnalysis: 'अहवाल विश्लेषण', healthCalculator: 'कॅल्क्युलेटर', medReminders: 'स्मरणपत्रे', reportsHub: 'अहवाल', posture: 'पवित्रा', firstAid: 'प्रथमोपचार', healthTips: 'आरोग्य टिप्स', emergency: 'आणीबाणी', howToUse: 'कसे वापरावे', settings: 'सेटिंग्ज', about: 'विषयी', more: 'अधिक', login: 'लॉगिन', signOut: 'साइन आउट', chatWithAI: 'AI चॅट', language: 'भाषा', analyze: 'विश्लेषण', upload: 'अपलोड', camera: 'कॅमेरा', capture: 'टिपा', cancel: 'रद्द', search: 'शोध', allHealthTools: 'सर्व साधने', tagline: 'आपले जीवन निरोगी बनवा!' },
  Telugu: { home: 'హోమ్', dashboard: 'డాష్‌బోర్డ్', symptoms: 'లక్షణాలు', skinInjury: 'చర్మం & గాయం', chat: 'చాట్', fitness: 'ఫిట్‌నెస్', medicine: 'మందు', vitals: 'ప్రాణ సంకేతాలు', reportAnalysis: 'నివేదిక విశ్లేషణ', healthCalculator: 'కాలిక్యులేటర్', medReminders: 'రిమైండర్లు', reportsHub: 'నివేదికలు', posture: 'భంగిమ', firstAid: 'ప్రాథమిక చికిత్స', healthTips: 'ఆరోగ్య చిట్కాలు', emergency: 'అత్యవసరం', howToUse: 'ఎలా ఉపయోగించాలి', settings: 'సెట్టింగ్‌లు', about: 'గురించి', more: 'మరిన్ని', login: 'లాగిన్', signOut: 'సైన్ అవుట్', chatWithAI: 'AI చాట్', language: 'భాష', analyze: 'విశ్లేషించండి', upload: 'అప్‌లోడ్', camera: 'కెమెరా', capture: 'క్యాప్చర్', cancel: 'రద్దు', search: 'శోధన', allHealthTools: 'అన్ని సాధనాలు', tagline: 'మీ జీవితాన్ని ఆరోగ్యకరంగా చేసుకోండి!' },
  Swahili: { home: 'Nyumbani', dashboard: 'Dashibodi', symptoms: 'Dalili', skinInjury: 'Ngozi na Jeraha', chat: 'Mazungumzo', fitness: 'Mazoezi', medicine: 'Dawa', vitals: 'Ishara Muhimu', reportAnalysis: 'Uchambuzi wa Ripoti', healthCalculator: 'Kikokotoo', medReminders: 'Vikumbusho', reportsHub: 'Ripoti', posture: 'Mkao', firstAid: 'Huduma ya Kwanza', healthTips: 'Vidokezo vya Afya', emergency: 'Dharura', howToUse: 'Jinsi ya Kutumia', settings: 'Mipangilio', about: 'Kuhusu', more: 'Zaidi', login: 'Ingia', signOut: 'Toka', chatWithAI: 'Mazungumzo ya AI', language: 'Lugha', analyze: 'Changanua', upload: 'Pakia', camera: 'Kamera', capture: 'Nasa', cancel: 'Ghairi', search: 'Tafuta', allHealthTools: 'Zana zote', tagline: 'Fanya maisha yako kuwa na afya bora!' },
  Greek: { home: 'Αρχική', dashboard: 'Πίνακας', symptoms: 'Συμπτώματα', skinInjury: 'Δέρμα & Τραυματισμός', chat: 'Συνομιλία', fitness: 'Φυσική κατάσταση', medicine: 'Φάρμακο', vitals: 'Ζωτικά σημεία', reportAnalysis: 'Ανάλυση αναφοράς', healthCalculator: 'Υπολογιστής', medReminders: 'Υπενθυμίσεις', reportsHub: 'Αναφορές', posture: 'Στάση', firstAid: 'Πρώτες βοήθειες', healthTips: 'Συμβουλές υγείας', emergency: 'Επείγον', howToUse: 'Πώς να χρησιμοποιήσετε', settings: 'Ρυθμίσεις', about: 'Σχετικά', more: 'Περισσότερα', login: 'Σύνδεση', signOut: 'Αποσύνδεση', chatWithAI: 'Συνομιλία AI', language: 'Γλώσσα', analyze: 'Ανάλυση', upload: 'Μεταφόρτωση', camera: 'Κάμερα', capture: 'Λήψη', cancel: 'Ακύρωση', search: 'Αναζήτηση', allHealthTools: 'Όλα τα εργαλεία', tagline: 'Κάνε τη ζωή σου πιο υγιή!' },
  Hebrew: { home: 'בית', dashboard: 'לוח בקרה', symptoms: 'תסמינים', skinInjury: 'עור ופציעה', chat: 'צ׳אט', fitness: 'כושר', medicine: 'תרופה', vitals: 'סימנים חיוניים', reportAnalysis: 'ניתוח דוח', healthCalculator: 'מחשבון', medReminders: 'תזכורות', reportsHub: 'דוחות', posture: 'יציבה', firstAid: 'עזרה ראשונה', healthTips: 'טיפים לבריאות', emergency: 'חירום', howToUse: 'איך להשתמש', settings: 'הגדרות', about: 'אודות', more: 'עוד', login: 'התחבר', signOut: 'התנתק', chatWithAI: 'צ׳אט AI', language: 'שפה', analyze: 'נתח', upload: 'העלה', camera: 'מצלמה', capture: 'צלם', cancel: 'ביטול', search: 'חיפוש', allHealthTools: 'כל הכלים', tagline: 'הפוך את חייך לבריאים יותר!' },
  Persian: { home: 'خانه', dashboard: 'داشبورد', symptoms: 'علائم', skinInjury: 'پوست و آسیب', chat: 'گفتگو', fitness: 'تناسب اندام', medicine: 'دارو', vitals: 'علائم حیاتی', reportAnalysis: 'تحلیل گزارش', healthCalculator: 'ماشین حساب', medReminders: 'یادآوری‌ها', reportsHub: 'گزارش‌ها', posture: 'حالت بدن', firstAid: 'کمک‌های اولیه', healthTips: 'نکات سلامتی', emergency: 'اضطراری', howToUse: 'نحوه استفاده', settings: 'تنظیمات', about: 'درباره', more: 'بیشتر', login: 'ورود', signOut: 'خروج', chatWithAI: 'گفتگو با هوش مصنوعی', language: 'زبان', analyze: 'تحلیل', upload: 'بارگذاری', camera: 'دوربین', capture: 'گرفتن', cancel: 'لغو', search: 'جستجو', allHealthTools: 'همه ابزارها', tagline: 'زندگی خود را سالم‌تر کنید!' },
  Ukrainian: { home: 'Головна', dashboard: 'Панель', symptoms: 'Симптоми', skinInjury: 'Шкіра і травми', chat: 'Чат', fitness: 'Фітнес', medicine: 'Ліки', vitals: 'Життєві показники', reportAnalysis: 'Аналіз звіту', healthCalculator: 'Калькулятор', medReminders: 'Нагадування', reportsHub: 'Звіти', posture: 'Постава', firstAid: 'Перша допомога', healthTips: 'Поради щодо здоров\'я', emergency: 'Екстрена', howToUse: 'Як користуватися', settings: 'Налаштування', about: 'Про нас', more: 'Більше', login: 'Увійти', signOut: 'Вийти', chatWithAI: 'AI чат', language: 'Мова', analyze: 'Аналізувати', upload: 'Завантажити', camera: 'Камера', capture: 'Зняти', cancel: 'Скасувати', search: 'Пошук', allHealthTools: 'Усі інструменти', tagline: 'Зроби своє життя здоровішим!' },
  Czech: { home: 'Domů', dashboard: 'Panel', symptoms: 'Příznaky', skinInjury: 'Kůže a zranění', chat: 'Chat', fitness: 'Fitness', medicine: 'Lék', vitals: 'Vitální znaky', reportAnalysis: 'Analýza zprávy', healthCalculator: 'Kalkulačka', medReminders: 'Připomínky', reportsHub: 'Zprávy', posture: 'Držení těla', firstAid: 'První pomoc', healthTips: 'Zdravotní tipy', emergency: 'Pohotovost', howToUse: 'Jak používat', settings: 'Nastavení', about: 'O nás', more: 'Více', login: 'Přihlásit', signOut: 'Odhlásit', chatWithAI: 'AI chat', language: 'Jazyk', analyze: 'Analyzovat', upload: 'Nahrát', camera: 'Kamera', capture: 'Zachytit', cancel: 'Zrušit', search: 'Hledat', allHealthTools: 'Všechny nástroje', tagline: 'Udělejte svůj život zdravější!' },
  Swedish: { home: 'Hem', dashboard: 'Instrumentpanel', symptoms: 'Symtom', skinInjury: 'Hud & skada', chat: 'Chatt', fitness: 'Träning', medicine: 'Medicin', vitals: 'Vitala tecken', reportAnalysis: 'Rapportanalys', healthCalculator: 'Kalkylator', medReminders: 'Påminnelser', reportsHub: 'Rapporter', posture: 'Hållning', firstAid: 'Första hjälpen', healthTips: 'Hälsotips', emergency: 'Nödsituation', howToUse: 'Hur man använder', settings: 'Inställningar', about: 'Om', more: 'Mer', login: 'Logga in', signOut: 'Logga ut', chatWithAI: 'AI-chatt', language: 'Språk', analyze: 'Analysera', upload: 'Ladda upp', camera: 'Kamera', capture: 'Ta bild', cancel: 'Avbryt', search: 'Sök', allHealthTools: 'Alla verktyg', tagline: 'Gör ditt liv hälsosammare!' },
};

const COMMON_KEYS = ['home','dashboard','symptoms','skinInjury','chat','fitness','medicine','vitals','reportAnalysis','healthCalculator','medReminders','reportsHub','posture','firstAid','healthTips','emergency','howToUse','settings','about','more','login','signOut','chatWithAI','language','analyze','upload','camera','capture','cancel','search','allHealthTools','tagline'];

export function useTranslation() {
  const [language] = useLocalStorage('healtify-language', 'English');

  const t = (key: string, fallback?: string): string => {
    const dict = translations[language as string];
    if (dict && dict[key]) return dict[key];
    // English fallback dictionary (sensible defaults)
    const en: Record<string, string> = {
      home: 'Home', dashboard: 'Dashboard', symptoms: 'Symptoms', skinInjury: 'Skin & Injury',
      chat: 'Chat', fitness: 'Fitness', medicine: 'Medicine', vitals: 'Vitals',
      reportAnalysis: 'Report Analysis', healthCalculator: 'Health Calculator',
      medReminders: 'Med Reminders', reportsHub: 'Reports Hub', posture: 'Posture',
      firstAid: 'First Aid', healthTips: 'Health Tips', emergency: 'Emergency',
      howToUse: 'How to Use', settings: 'Settings', about: 'About', more: 'More',
      login: 'Login', signOut: 'Sign Out', chatWithAI: 'Chat with AI', language: 'Language',
      analyze: 'Analyze', upload: 'Upload', camera: 'Camera', capture: 'Capture',
      cancel: 'Cancel', search: 'Search', allHealthTools: 'All Your Health Tools',
      tagline: 'Make your life healthier !',
    };
    return en[key] || fallback || key;
  };

  return { t, language, supportedKeys: COMMON_KEYS };
}
