import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Trash2, Search, Calendar, Pill, TrendingUp, Download, Scan, Dumbbell, Apple, Stethoscope, X, ExternalLink, Activity, FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useLocalStorage } from '@/hooks/useLocalStorage';
import { PageHeader } from '@/components/PageHeader';

interface HealthReport {
  id: string;
  type: string;
  title: string;
  date: string;
  summary: string;
  details?: string;
}

const typeIcons: Record<string, any> = {
  'skin-analysis': Scan,
  'injury-analysis': Scan,
  medication: Pill,
  medicine: Pill,
  diet: Apple,
  workout: Dumbbell,
  symptoms: Stethoscope,
  vitals: Activity,
  bmi: TrendingUp,
};

function downloadAsPDF(report: HealthReport) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = margin;

  // Header band
  doc.setFillColor(44, 163, 191);
  doc.rect(0, 0, pageW, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('Healthier', margin, 38);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('AI Health Assistant — Make your life healthier', margin, 56);
  y = 100;

  // Meta line
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  doc.text(`Date: ${report.date}`, margin, y);
  doc.text(`Type: ${report.type.replace(/-/g, ' ').toUpperCase()}`, pageW - margin, y, { align: 'right' });
  y += 22;

  // Title
  doc.setTextColor(20, 20, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(report.title, pageW - 2 * margin);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 20 + 10;

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageW - margin, y);
  y += 18;

  // Body
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  const body = report.details || report.summary || '';
  const lines = doc.splitTextToSize(body, pageW - 2 * margin);
  for (const line of lines) {
    if (y > pageH - margin - 80) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 14;
  }

  // Disclaimer footer
  if (y > pageH - margin - 80) { doc.addPage(); y = margin; }
  y = pageH - 90;
  doc.setFillColor(255, 248, 220);
  doc.rect(margin, y, pageW - 2 * margin, 50, 'F');
  doc.setTextColor(120, 80, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Important Disclaimer', margin + 10, y + 16);
  doc.setFont('helvetica', 'normal');
  const disc = doc.splitTextToSize(
    'This AI-generated report is for informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional. Healthier does not prescribe medications.',
    pageW - 2 * margin - 20
  );
  doc.text(disc, margin + 10, y + 30);

  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text(`Generated by Healthier · ${new Date().toLocaleString()} · © ${new Date().getFullYear()}`, pageW / 2, pageH - 20, { align: 'center' });

  const safeTitle = report.title.replace(/[^a-z0-9]/gi, '-').slice(0, 50);
  doc.save(`healthier-${safeTitle}-${report.date}.pdf`);
}

export default function HealthReportsPage() {
  const [search, setSearch] = useState('');
  const [selectedType, setSelectedType] = useState<string>('all');
  const [reports, setReports] = useLocalStorage<HealthReport[]>('healthier-reports', []);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [viewingReport, setViewingReport] = useState<HealthReport | null>(null);

  const sorted = useMemo(() => {
    return [...reports]
      .sort((a, b) => b.date.localeCompare(a.date))
      .filter(r => {
        const matchSearch = !search || r.title.toLowerCase().includes(search.toLowerCase()) || r.summary.toLowerCase().includes(search.toLowerCase());
        const matchType = selectedType === 'all' || r.type === selectedType;
        return matchSearch && matchType;
      });
  }, [reports, search, selectedType]);

  const types = useMemo(() => {
    const set = new Set(reports.map(r => r.type));
    return ['all', ...Array.from(set)];
  }, [reports]);

  const exportAll = () => {
    const data = JSON.stringify(reports, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `healthier-reports-${new Date().toISOString().split('T')[0]}.json`; a.click();
    URL.revokeObjectURL(url);
  };

  const downloadSingle = (report: HealthReport) => {
    const data = JSON.stringify(report, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `report-${report.type}-${report.date}.json`; a.click();
    URL.revokeObjectURL(url);
  };

  const deleteReport = (id: string) => {
    setReports(prev => prev.filter(r => r.id !== id));
    if (viewingReport?.id === id) setViewingReport(null);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto">
        <PageHeader
          icon={<TrendingUp className="h-8 w-8 text-primary-foreground" />}
          title="Health Reports"
          description="Auto-generated from your tool usage — view, download as PDF, or delete anytime"
          gradient="from-primary to-success"
          showEmergency={false}
        />

        <AnimatePresence>
          {viewingReport && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4"
              onClick={() => setViewingReport(null)}>
              <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
                className="bg-card rounded-2xl border border-border shadow-xl max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col"
                onClick={e => e.stopPropagation()}>
                <div className="flex items-center justify-between p-4 border-b border-border">
                  <div>
                    <h3 className="font-semibold">{viewingReport.title}</h3>
                    <p className="text-xs text-muted-foreground">{viewingReport.date} · {viewingReport.type}</p>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => downloadAsPDF(viewingReport)}><FileDown className="w-3 h-3 mr-1" />PDF</Button>
                    <Button size="sm" variant="outline" onClick={() => downloadSingle(viewingReport)}><Download className="w-3 h-3 mr-1" />JSON</Button>
                    <button onClick={() => setViewingReport(null)} className="p-2 rounded-lg hover:bg-muted"><X className="w-4 h-4" /></button>
                  </div>
                </div>
                <div className="p-6 overflow-y-auto flex-1">
                  <p className="text-sm text-muted-foreground whitespace-pre-wrap">{viewingReport.details || viewingReport.summary}</p>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="grid grid-cols-3 gap-3 mb-6">
          <div className="bg-card rounded-xl p-4 border border-border text-center">
            <p className="text-2xl font-bold text-primary">{reports.length}</p>
            <p className="text-xs text-muted-foreground">Total Reports</p>
          </div>
          <div className="bg-card rounded-xl p-4 border border-border text-center">
            <p className="text-2xl font-bold text-primary">{new Set(reports.map(r => r.type)).size}</p>
            <p className="text-xs text-muted-foreground">Categories</p>
          </div>
          <div className="bg-card rounded-xl p-4 border border-border text-center">
            <p className="text-2xl font-bold text-primary">{reports.filter(r => r.date === new Date().toISOString().split('T')[0]).length}</p>
            <p className="text-xs text-muted-foreground">Today</p>
          </div>
        </div>

        <div className="flex gap-3 mb-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input placeholder="Search reports..." value={search} onChange={e => setSearch(e.target.value)} className="pl-10" />
          </div>
          <Button variant="outline" onClick={exportAll} className="gap-2" disabled={reports.length === 0}>
            <Download className="w-4 h-4" /> Export All
          </Button>
        </div>

        <div className="flex flex-wrap gap-2 mb-6">
          {types.map(t => (
            <button key={t} onClick={() => setSelectedType(t)}
              className={`px-3 py-1.5 rounded-full text-sm font-medium capitalize transition-all ${selectedType === t ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-muted/80'}`}>
              {t.replace('-', ' ')}
            </button>
          ))}
        </div>

        <div className="space-y-3">
          {sorted.map(report => {
            const Icon = typeIcons[report.type] || FileText;
            const isExpanded = expandedId === report.id;
            return (
              <motion.div key={report.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                className="bg-card rounded-xl border border-border overflow-hidden">
                <button onClick={() => setExpandedId(isExpanded ? null : report.id)}
                  className="w-full flex items-center gap-4 p-4 text-left hover:bg-muted/30 transition-colors">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center bg-primary/10 shrink-0">
                    <Icon className="w-5 h-5 text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-sm truncate">{report.title}</h3>
                    <p className="text-xs text-muted-foreground truncate">{report.summary}</p>
                  </div>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground shrink-0">
                    <Calendar className="w-3 h-3" />{report.date}
                  </div>
                </button>
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">
                      <div className="px-4 pb-4 pt-1 border-t border-border">
                        <p className="text-sm text-muted-foreground whitespace-pre-wrap mb-3">
                          {report.details ? report.details.slice(0, 300) + (report.details.length > 300 ? '...' : '') : report.summary}
                        </p>
                        <div className="flex gap-2">
                          <Button size="sm" variant="outline" onClick={(e) => { e.stopPropagation(); setViewingReport(report); }}>
                            <ExternalLink className="w-3 h-3 mr-1" />Open
                          </Button>
                          <Button size="sm" variant="outline" onClick={(e) => { e.stopPropagation(); downloadAsPDF(report); }}>
                            <FileDown className="w-3 h-3 mr-1" />PDF
                          </Button>
                          <Button size="sm" variant="outline" onClick={(e) => { e.stopPropagation(); downloadSingle(report); }}>
                            <Download className="w-3 h-3 mr-1" />JSON
                          </Button>
                          <Button size="sm" variant="outline" className="text-destructive hover:bg-destructive/10" onClick={(e) => { e.stopPropagation(); deleteReport(report.id); }}>
                            <Trash2 className="w-3 h-3 mr-1" />Delete
                          </Button>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

        {sorted.length === 0 && (
          <div className="text-center py-16">
            <FileText className="w-16 h-16 text-muted-foreground/30 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">No reports yet</h3>
            <p className="text-muted-foreground">Reports are auto-generated when you use health tools like Skin Analyzer, Medicine Info, or Fitness Planner</p>
          </div>
        )}
      </div>
    </div>
  );
}
