// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Get the signed-in Healthier user's profile (full name, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("full_name, avatar_url, created_at, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/update-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var update_profile_default = defineTool2({
  name: "update_profile",
  title: "Update my profile",
  description: "Update the signed-in Healthier user's display name or avatar URL.",
  inputSchema: {
    full_name: z.string().trim().min(1).max(120).optional().describe("New display name."),
    avatar_url: z.string().url().optional().describe("New avatar image URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ full_name, avatar_url }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!full_name && !avatar_url) {
      return { content: [{ type: "text", text: "Provide full_name or avatar_url." }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const patch = {};
    if (full_name) patch.full_name = full_name;
    if (avatar_url) patch.avatar_url = avatar_url;
    const { data, error } = await supabase.from("profiles").update(patch).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/health-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var health_info_default = defineTool3({
  name: "health_info",
  title: "General health information",
  description: "Ask Healthier's medical assistant for general, non-emergency health information about a topic, symptom, or medication. Returns educational content only \u2014 never a diagnosis or prescription.",
  inputSchema: {
    topic: z2.string().trim().min(2).max(500).describe("The health topic or question.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ topic }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const apiKey = process.env.LOVABLE_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    }
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: "You are Healthier AI. Provide concise, educational health information (150-250 words). Never diagnose or prescribe. Always advise consulting a doctor for serious concerns. Include a short disclaimer."
          },
          { role: "user", content: topic }
        ]
      })
    });
    if (!res.ok) {
      const errText = await res.text();
      return { content: [{ type: "text", text: `AI error: ${res.status} ${errText}` }], isError: true };
    }
    const json = await res.json();
    const text = json?.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text }], structuredContent: { topic, answer: text } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ewnxnvtnkcexwzfnaawp";
var mcp_default = defineMcp({
  name: "healthier-mcp",
  title: "Healthier",
  version: "0.1.0",
  instructions: "Healthier is an AI health assistant. Tools let the signed-in user read/update their profile and ask general (non-emergency) health questions. Never provide diagnoses, prescriptions, or emergency medical advice \u2014 direct users to professional care for anything serious.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, update_profile_default, health_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
